adapp/ads/routes.py
from flask import Blueprint, render_template, url_for, redirect, abort, request, flash
from flask_login import login_required, current_user
from datetime import datetime
from adapp.ads.forms import CreatingAdForm, PickUserForm, FinishAdForm
from adapp import db
from adapp.models import Ad, User

ads = Blueprint('ads', __name__)

@ads.route('/create_ad', methods=['POST', 'GET'])
@login_required
def create_ad():
    form = CreatingAdForm()
    if form.validate_on_submit():
        new_ad = Ad(title=form.title.data, content=form.content.data, date_of_create=datetime.now(), reward=form.reward.data)
        new_ad.user_id = current_user.id
        db.session.add(new_ad)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template('create_ad.html', form=form, legend='Create ad!')

@ads.route('/ad_detail/<int:ad_id>')
def ad_detail(ad_id):
    ad = Ad.query.get_or_404(ad_id)
    form = PickUserForm()
    finish_form = FinishAdForm()
    return render_template('ad_detail.html', ad=ad, form=form, finish_form=finish_form)

@ads.route('/ad_update/<int:ad_id>', methods=['GET', 'POST'])
@login_required
def update_ad(ad_id):
    ad = Ad.query.get_or_404(ad_id)
    if ad.author != current_user:
        abort(404)
    form = CreatingAdForm()
    if request.method == 'GET':
        form.title.data = ad.title
        form.content.data = ad.content
        form.reward.data = ad.reward
    elif form.validate_on_submit():
        ad.title = form.title.data
        ad.content = form.content.data
        ad.reward = form.reward.data
        db.session.commit()
        flash('Successfully updated!', 'success')
        return redirect(url_for('ad_detail', ad_id=ad.id))
    return render_template('create_ad.html', ad=ad, legend='Update ad!', form=form)

@ads.route('/delete_ad/<int:ad_id>')
@login_required
def delete_ad(ad_id):
    ad = Ad.query.get_or_404(ad_id)
    if ad.author != current_user:
        abort(404)
    db.session.delete(ad)
    db.session.commit()
    return redirect(url_for('main.home'))

@ads.route('/sign_in/<int:ad_id>')
@login_required
def sign_in(ad_id):
    ad = Ad.query.get_or_404(ad_id)
    if ad.is_finished:
        flash('This ad is already finished, you cannot sign in!')
    ad.users.append(current_user)
    db.session.commit()
    return redirect(url_for('ads.ad_detail', ad_id=ad.id))

@ads.route('/pick_user/<int:ad_id><int:user_id>', methods=['POST'])
@login_required
def pick_user(ad_id, user_id):
    ad = Ad.query.get_or_404(ad_id)
    user = User.query.get_or_404(user_id)
    form = PickUserForm()
    finish_form = FinishAdForm()
    if form.validate_on_submit():
        user.picked_for_ads.append(ad)
        db.session.commit()
    return render_template('ad_detail.html', ad=ad, form=form, user=user, finish_form=finish_form)

@ads.route('/finish_ad/<int:ad_id>', methods=['GET', 'POST'])
@login_required
def finish_ad(ad_id):
    ad = Ad.query.get_or_404(ad_id)
    if ad.author != current_user or ad.picked_for is None:
        abort(404)
    finish_form = FinishAdForm()
    if finish_form.validate_on_submit():
        ad.is_finished = True
        db.session.commit()
        return redirect(url_for('rates.rate_user', user_id=ad.picked_for.id, ad_id=ad.id))
    return render_template('ad_detail.html', ad=ad, finish_form=finish_form)

adapp/messagess/routes.py
from flask import Blueprint, render_template, url_for, redirect
from flask_login import login_required, current_user
from datetime import datetime
from adapp.models import Ad, User, Message
from adapp.messagess.forms import CreateMessageForm
from adapp import db

messagess = Blueprint('messagess', __name__)

@messagess.route('/send_message/<int:user_id>', methods=['POST', 'GET'])
@login_required
def send_message(user_id):
    user = User.query.get_or_404(user_id)
    form = CreateMessageForm()
    if form.validate_on_submit():
        new_message = Message(content=form.content.data, by=current_user, to=user, date_of_create=datetime.now())
        db.session.add(new_message)
        db.session.commit()
        return redirect(url_for('users.user_detail', user_id=user.id))
    return render_template('send_message.html', form=form, user=user)

@messagess.route('/inbox')
@login_required
def inbox():
    messages = current_user.messages_received
    return render_template('inbox.html', messages=messages)

adapp/users/routes.py
from flask import Blueprint, render_template, url_for, redirect, abort, request, flash
from flask_login import login_required, current_user, login_user, logout_user
from adapp.users.forms import RegistrationForm, EditProfileForm, LoginForm
from adapp.models import User
from adapp import db, bcrypt

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        new_user = User(email=form.email.data, password=hashed_password, name=form.name.data)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash('You are already logged in')
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for('main.home'))
        else:
            flash('Wrong email or password!')
    return render_template('login.html', form=form)

@users.route('/logout')
def logout():
    logout_user()
    flash('Successfully logged out!', 'success')
    return redirect(url_for('main.home'))

@users.route('/user_detail/<int:user_id>')
@login_required
def user_detail(user_id):
    user = User.query.get_or_404(user_id)
    if current_user == user:
        return redirect(url_for('users.update_profile', user_id=current_user.id))
    return render_template('user_detail.html', user=user)

@users.route('/update_profile/<int:user_id>', methods=['GET', 'POST'])
@login_required
def update_profile(user_id):
    user = User.query.get_or_404(user_id)
    if current_user != user:
        abort(404)
    form = EditProfileForm()
    if form.validate_on_submit():
        user.description = form.description.data
        db.session.commit()
        flash('Profile updated!')
    elif request.method == 'GET':
        form.description.data = user.description
    return render_template('update_profile.html', form=form)

adapp/templates/ad_detail.html
{% extends 'base.html' %}

{% block title %}Detail Ad Page{% endblock %}

{% block content %}
    <p>Title: {{ ad.title }}</p>
    <p>Content: {{ ad.content }}</p>
    <p>Created by: <a href="{{ url_for('users.user_detail', user_id=ad.author.id) }}">{{ ad.author }}</a></p>
    <p>Created: {{ ad.date_of_create.strftime('%Y-%m-%d %H:%M:%S') }}</p>
    {% if ad.author != current_user and current_user not in ad.users and ad.picked_for is none %}
        <p><a href="{{ url_for('ads.sign_in', ad_id=ad.id) }}">Sign in this ad</a></p>
    {% endif %}
    {% if ad.author == current_user and ad.picked_for %}
        <p>For this ad you picked user: <a href="{{ url_for('users.user_detail', user_id=ad.picked_for.id) }}">{{ ad.picked_for }}</a></p>
        <p>Now you can <a href="{{ url_for('messagess.send_message', user_id=ad.picked_for.id) }}">contact him</a></p>
        <form action="{{ url_for('ads.finish_ad', ad_id=ad.id) }}" method="POST">
            {{ finish_form.hidden_tag() }}
            {{ finish_form.submit }}
        </form>
    {% endif %}
    {% if ad.author == current_user %}
        <a href="{{ url_for('ads.delete_ad', ad_id=ad.id) }}">Delete ad</a>
        <a href="{{ url_for('ads.update_ad', ad_id=ad.id) }}">Update ad</a>
        <legend>Users signed in this ad</legend>
        {% for user in ad.users %}
            {% if ad not in user.picked_for_ads %}
            <p><a href="{{ url_for('users.user_detail', user_id=user.id) }}">{{ user }}</a></p>
            <form action="{{ url_for('ads.pick_user', ad_id=ad.id, user_id=user.id) }}" method="POST">
                {{ form.hidden_tag() }}
                {{ form.submit }}
            </form>
            {% endif %}
        {% endfor %}
    {% elif ad.author != current_user and current_user in ad.users %}
            <legend>You are signed in to this ad! You must wait for editor's pick!</legend>
    {% endif %}
{% endblock %}

adapp/templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">Quest</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('main.home') }}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        {% if current_user.is_authenticated %}
                            <a class="nav-link" href="{{ url_for('users.user_detail', user_id=current_user.id)}}">{{current_user.name}}</a>
                            
                        {% else %}
                            
                            <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                        {% endif %}
                    </li>
                    <li class="nav-item active">
                        {% if  current_user.is_authenticated %}
                            <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                        <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                    </li>
                    <li class="nav-item active">
                        {% if  current_user.is_authenticated %}
                            <a class="nav-link" href="{{ url_for('ads.create_ad') }}">Create ad!</a>
                            
                        {% endif %}
                    </li>
                    <li class="nav-item active">
                        {% if  current_user.is_authenticated %}
                            <a class="nav-link" href="{{ url_for('messagess.inbox')}}">Inbox</a>
                        {% endif %}
                    </li>
                    
                </ul>
            </div>
        </nav>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    </head>
    <body>
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <ul class=flashes>
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}
        </div>
        {% block content %}
            
        {% endblock %}

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    </body>
</html>

adapp/templates/create_ad.html
{% extends 'base.html' %}

{% block title %}Create Ad Page{% endblock %}

{% block content %}
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <legend>{{ legend }}</legend>
        <p>{{ form.title.label }} {{ form.title }}</p>
        <p>{{ form.content.label }} {{ form.content }}</p>
        <p>{{ form.reward.label }} {{ form.reward }}</p>
        {{ form.submit }}
    </form>
{% endblock%}

adapp/templates/home.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
    {% for ad in ads %}
        {% if ad.is_finished == False %}
        <article class="media content-section">
            <div class="media-body">
                <h1><a href="{{ url_for('ads.ad_detail', ad_id=ad.id)}}">{{ad.title}}</a></h1>
                <p>Created by: <a href="{{ url_for('users.user_detail', user_id=ad.author.id)}}">{{ad.author.name}}</a></p>
                <p>Created: {{ad.date_of_create.strftime('%Y-%m-%d %H:%M:%S')}}</p>
                {% if ad.picked_for %}
                    <legend>The editor has already picked someone for this ad!</legend>
                {% endif %}
            </div>
        </article>
        {% endif %}
    {% endfor %}
{% endblock %}

adapp/templates/inbox.html
{% extends 'base.html' %}

{% block title %}Inbox Page{% endblock %}

{% block content %}
    {% for message in messages %}
        <p>Message from: <a href="{{ url_for('users.user_detail', user_id=message.by.id) }}">{{ message.by }}</a></p>
        <p>Received: {{ message.date_of_create.strftime('%Y-%m-%d %H:%M:%S') }}</p>
        <p>Message content: {{ message.content }}</p>
        <p><a href="{{ url_for('messages.send_message', user_id=message.by.id) }}">Reply</a></p>
    {% endfor %}
{% endblock %}

adapp/templates/login.html
{% extends 'base.html' %}

{% block title %}Login Page{% endblock %}

{% block content %}
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <legend>Login</legend>
        <p>{{ form.email.label }} {{ form.email }}</p>
        <p>{{ form.password.label }} {{ form.password }}</p>
        <p>{{ form.remember.label }} {{ form.remember }}</p>
        {{ form.submit }}
    </form>
{% endblock%}

adapp/templates/rate_user.html
{% extends 'base.html' %}

{% block title %}Rate User{% endblock %}

{% block content %}
    <form action="" method="POST">
        <legend>Did you like coop with ?</legend>
        {{ form.hidden_tag() }}
        <p>{{ form.rate.label }} {{ form.rate }}</p>
        <p>{{ form.comment.label }} {{ form.comment }}</p>
        <p>{{ form.submit }}</p>
    </form>
{% endblock %}

adapp/templates/register.html
{% extends 'base.html' %}

{% block title %}Register Page{% endblock %}

{% block content %}
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <legend>Register now!</legend>
        <p>{{ form.email.label }} {{ form.email }}</p>
        <p>{{ form.name.label }} {{ form.name }}</p>
        <p>{{ form.password.label }} {{ form.password }}</p>
        <p>{{ form.confirm_password.label }} {{ form.confirm_password }}</p>
        <p>{{ form.description.label }} {{ form.description }}</p>
        {{ form.submit }}
    </form>
{% endblock %}

adapp/templates/send_message.html
{% extends 'base.html' %}

{% block title %}Send Message Page{% endblock %}

{% block content %}
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <p>{{ form.content.label }} {{ form.content }}</p>
        {{ form.submit }}
    </form>
{% endblock%}

adapp/templates/update_profile.html
{% extends 'base.html' %}

{% block title %}Update Profile Page{% endblock %}

{% block content %}
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <legend>Update {{ current_user.name }}'s Profile</legend>
        <p>{{ form.description.label }} {{ form.description }}</p>
        {{ form.submit }}
        <p>My rating: {{ current_user.rating }}</p>
    </form>
{% endblock %}

adapp/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}{{ user.name }}'s Profile{% endblock %}

{% block content %}
    <p>About user: {{ user.description }}</p>
    <p>User's rating: {{ user.rating }}</p>
    <p>Comments about user:</p>
    {% for comment in user.comments_received %}
        <p>{{ comment.content }}</p>
        <p>Created by: {{ comment.by }}</p>
    {% endfor %}
{% endblock %}